### PR TITLE
Bump alarm/kodi-c1-fb to 16.0b2

### PR DESCRIPTION
**Pull request by Holzhaus**
This bumps the kodi-c1-fb package to version 16.0 beta 2 (Jarvis).

This package now uses the mainline kodi repo. See this for details:
http://forum.odroid.com/viewtopic.php?f=112&t=15158&start=200#p113959

### CODE REVIEW

**Comment by Holzhaus** [comment]
I compiled with gcc 5.2 and it still crashed shortly after starting, so I'm recompiling with gcc 5.1. Didn't have the time to test it.

**Comment by Apokalypzx** [comment]
Do the crashes still have to do with the video library or is it completely separate? Because I don't have the GCC 5.1 package (and I'll bet most others don't either). So by removing the requirement for an earlier GCC in the package as it stands before this PR, it still built and ran successfully; though I don't use the video library at all.

**Comment by Holzhaus** [comment]
> Do the crashes still have to do with the video library?

I think so, because they behave exactly like the crashes in 15.2. Kodi's splash screen showed, then the custom skin came up, and it crashed while showing "Loading library contents...". Didn't check the logs or tried with a clean `~/.kodi` folder though.

> Because I don't have the GCC 5.1 package (and I'll bet most others don't either).

I had the same problem and [asked in the ALARM forums](http://archlinuxarm.org/forum/viewtopic.php?f=60&t=9284) and was pointed to a repo mirror that still has them: http://fraggod.net/static/mirror/packages/archlinuxarm/armv7h/

Anyway, I recompiled with GCC 5.1 and it doesn't crash anymore....unless I want to watch a movie.

I found this in the logs:

```
11:29:17 T:2900357968   ERROR: Unable to load libamplayer.so, reason: libamplayer.so: cannot open shared object file: No such file or directory
```

I'll investigate.

**Comment by Apokalypzx** [comment]
That missing libamplayer.so is actually an old problem that was patched in the hardkernel kodi branch. From what I remember, the C1 amlogic libs malefile doesn't actually make a "libamplayer.so", they make a "amcodec.so" instead, as libamplayer.so is the ?old? version of the lib...I think.

**Comment by Apokalypzx** [comment]
For my previous comment:
I was correct. In /xbmc/cores/dvdplayer/DVDcodecs/video/AMLcodec.cpp
There is a line (I'm on mobile right now so it doesn't show line numbers) that says the codec lib name.

Hardkernel's branch:
DECLARE_DLL_WRAPPER(DllLibAmCodec, "libamcodec.so")

Mainline KODI branch:
DECLARE_DLL_WRAPPER(DllLibAmCodec, "libamplayer.so")

**Comment by Holzhaus** [comment]
Found it: https://github.com/xbmc/xbmc/blob/f42c66f130805765b0c30d947980d5f2af847cde/xbmc/cores/dvdplayer/DVDCodecs/Video/AMLCodec.cpp#L106-L107

Do you know if this is something specific to the ODROID-C1? Or does this affect _all_ amlogic devices? Just wondering if I should send a patch to upstream kodi. After https://github.com/koying/xbmc/commit/20cd046f9633cb505c0f651d54bc9f807d87c86d has been merged, this might be the only thing keeping us from running vanilla kodi code.

**Comment by Holzhaus** [comment]
I'm currently recompiling with this patch: https://github.com/Holzhaus/alarm-PKGBUILDs/blob/2ccde45b37ba63b7646eae89ad29bdcd071d40ba/alarm/kodi-c1-fb/0014-aml-Remove-dependency-on-libamplayer-and-amffmpeg.patch

**Comment by Holzhaus** [comment]
I can confirm that the latest version of this PKGBUILD is working fine for me.

**Comment by Apokalypzx** [comment]
Well, if it works, I shall add it. Thanks. Hopefully the KODI devs will actually get around to fixing the GCC 5.2 issues sometime.

**Comment by Holzhaus** [comment]
Yeah. Meanwhile, I'll try to get a patch for the `libamlplayer` issue merged upstream, so that we can run vanilla kodi at some point.

**Comment by Holzhaus** [comment]
Looks like the patches are going to be merged into upstream before 16.0 Jarvis beta 3: https://github.com/xbmc/xbmc/pull/8449

**Comment by Apokalypzx** [comment]
Looks like they merged, but renamed the git to 17 alpha. I updated the PKGBUILD, removed the old patches, and moved the kodi-c1-fb to it's own repository since there seems to be zero chance of getting it into archlinuxarm's official repo. New repo URL:  https://github.com/Apokalypzx/kodi-c1-fb

**Pull request merged**
