### PR TITLE
alarm/kodi-c1-fb: Bump version to 15.0 final

### PR DESCRIPTION
**Pull request by Holzhaus**
Hardkernel seems to use Owersuns xbmc repo now:
http://forum.odroid.com/viewtopic.php?f=111&t=14278#p99718

### CODE REVIEW

**Comment by Apokalypzx** [comment]
Thank you Jan, I was just considering switching yesterday. You're one step ahead of me.

**Comment by Holzhaus** [comment]
By the way, mdrjr has posted his configure flags [here](http://forum.odroid.com/viewtopic.php?f=111&t=14278#p99812).

This raises some questions: Can we use `--enable-neon` too?

Also, why do we `--disable-texturepacker`? According to [wiki](http://kodi.wiki/view/TexturePacker), that should make things faster:

> Kodi uses a tool named TexturePacker to compile all images used in a skin into a single file. The benefit of it is that images inside the Textures.xbt will load faster in the skin. This is done by converting all images into a format that take less processing by Kodi when they need to be rendered onto the screen.

**EDIT:** Looks like mdrjr uses both `--enable-texturepacker` and `--disable-texturepacker`, so I guess that has to be disabled.

**Comment by Apokalypzx** [comment]
Looking through configure.ac doesn't show --enable-neon as an option. So I'm not sure it's even implemented. Though there is a cflag option I'm experimenting with right now called "-mvectorize-with-neon-quad". It is in the configure.ac file, enabled for certain chipsets like tegra3, but doesn't look like there is a way to enable it by itself in the configure options. So I'm adding it manually to the CFLAGS in the pkgbuild to test it. Will push if it works.

--disable-texturepacker was disabled on mdrjr's build (though I did see where he enabled and disabled it at the same time... I dont know what that's about.) and a few other builds for other devices so I disabled it as well in this build. I'll make a package with it enabled and test it for a while, if it works then I'll push it to the git.

As far as --enable-ccache, it is primarily for subsequent rebuilds. I don't think this would help at all since once arch builds a package, rebuilding the package would clean and redownload the source and wipe any ccache that was created on the last build, making the option pointless. I will test this one out as well, I guess if it doesn't break the build or break KODI, it's not doing any harm by adding it.

**Comment by Holzhaus** [comment]
Thanks for the detailed explanation!

**Comment by Apokalypzx** [comment]
Just confirmed by attempting to build it, enabling texturepacker or ccache breaks the configure step of the build.

**Comment by jmarcet** [comment]
The issue with texturerepacker is because it tries to do a static build.

https://github.com/jmarcet/kodi/commit/c61bbfc2d76452bbcae2a2d883ac274d701d03de should fix it and the texturerepacker option enabled with no problems.

**Comment by Holzhaus** [comment]
Just encountered a strange bug. I cannot use the Database. Had to delete my ~/.kodi/userdata/Database folder, because Kodi would crash after some time if I didn't. As soon as I try to scan my library kodi will crash. can you reproduce?

**Comment by Apokalypzx** [comment]
I just scanned in my library and I didn't see the bug you are talking about. Did you delete your .kodi folder after the upgrade? I know kodi usually has issues if you keep your home folder between versions. In fact mine kept restarting until I deleted the home folder and let kodi remake it.

**Comment by Holzhaus** [comment]
Yup, that restarting happened to me too (because it crashed). I fixed it by deleting the Database folder. I'll try to delete the whole ~/.kodi folder and check if the issue persists.

**Comment by Holzhaus** [comment]
I removed the `~/.kodi` folder and started kodi. Everything was fine. But 2 or 3 minutes after I started the library scan, kodi crashed again and now keeps restarting because of a core dump. The only piece of info I can find is this (via `journalctl`):

```
Aug 06 01:32:00 odroid-c1 kodi[2521]: libpng warning: iCCP: known incorrect sRGB profile
Aug 06 01:32:00 odroid-c1 kodi[2521]: libpng warning: iCCP: known incorrect sRGB profile
Aug 06 01:32:00 odroid-c1 kodi[2521]: libpng warning: iCCP: known incorrect sRGB profile
Aug 06 01:32:35 odroid-c1 kodi[2521]: /usr/bin/kodi: Line 165:  2523 Segmentation fault (core dumped) "$LIBDIR/${bin_name}/${bin_name}.bin" $SAVED_ARGS
Aug 06 01:32:36 odroid-c1 kodi[2521]: Crash report available at /var/lib/kodi/kodi_crashlog-20150806_013235.log
```

I can't really find any hints what happend in the crash report itself:
http://pastebin.com/52bKB5E4

**EDIT:** Looks like I have to use kodi with folder navigation for now. That works. Just watched a 3 hour movie without any problems. I'll recompile in a week or two with a more recent commit and check if that issue is still there.

**Comment by Apokalypzx** [comment]
Did you install any addons? I traced my problem to an addon.

**Comment by Holzhaus** [comment]
Just the [Arctic Zephyr Skin](http://forum.kodi.tv/showthread.php?tid=217174). But that one works as long as I don't have a library. And with my clean `~/.kodi` dir, I just installed it, didn't activate or ran it. On the other hand, it could be one of its dependencies. I'll remove the `~/.kodi` dir again and _only_ scan the library, nothing else.

**Comment by Holzhaus** [comment]
Hmm, looks like the problem is not the library scan, but the "Movies" menu. I scanned my whole library (with a clean "~/.kodi" dir and no addons), and everything went fine. As soon as I pressed the right arrow key to navigate from the "Videos" entry to the "Movies" entry in the main menu, kodi crashed again (because that entry displays "Recently Added Movies" I assume).

**Comment by Apokalypzx** [comment]
I found something similar on the arch forums for the iMX6 devices:
http://archlinuxarm.org/forum/viewtopic.php?f=60&t=9123

Not sure what they mean by their solution though.

**Pull request merged**
