### PR TITLE
[alarm/kodi-c1-fb] Fix pkgver/pkgrel

### PR DESCRIPTION
**Pull request by Holzhaus**
This PR fixed the PKGBUILD version, fixes mixed indentation (tabs were converted to spaces) and adds sha256sums. See the individual commit messages for details.

### CODE REVIEW

**Comment by Holzhaus** [comment]
I googled it and found [this](https://www.mail-archive.com/arch-commits@archlinux.org/msg115060.html). Might have been an exception though:

```
 _LOver=4.0.0.0.alpha1
 pkgver=4.0.0
-pkgrel=0.alpha1.1
+pkgrel=0.alpha1.2
```

**Comment by Apokalypzx** [comment]
I'm thinking that is an exception as that particular usage seems very rare. The pkgrel is about the pkgbuild. The pkgver is about the software. Since it's being built from a git repo that progresses on a regular basis, the terms alpha and beta don't really apply since this beta will be different from their official released beta. I think it would be better to apply a date suffix to the pkgver as most packages built from an ever changing git do.

**Comment by Apokalypzx** [comment]
I added a commit to fix pkgver and pkgrel. If you could resubmit your PR with only the other 2 commits, I'll look it over and merge it so you get the credit for your contribution.

**Comment by Apokalypzx** [comment]
On 2nd thought. It might be easier to revert my last commit, merge this PR, then make the pkgver and pkgrel changes again on top.

**Comment by Holzhaus** [comment]
Check out [`git cherry-pick`](https://ariejan.net/2010/06/10/cherry-picking-specific-commits-from-another-branch/)

**Pull request merged**
